ceph_origin: repository
ceph_repository: community
ceph_stable_release: jewel
public_network: "192.168.94.0/16"
cluster_network: "192.168.4.0/16"
monitor_interface: eth0
devices:
  - '/dev/sdb'
osd_scenario: collocated
os_tuning_params:
  - { name: fs.file-max, value: 26234859 }
  - { name: vm.zone_reclaim_mode, value: 0 }
  - { name: vm.swappiness, value: 0 }
  - { name: vm.min_free_kbytes, value: "{{ vm_min_free_kbytes }}" }
cluster: ceph
